In [1]:
import numpy as np

In [6]:
s=np.array(5)
s.shape

()

In [5]:
s+=5
print(s)

15


In [7]:
v = np.array([1,2,3])
v.shape

(3,)

In [8]:
v[1]

2

In [10]:
v[1:]

array([2, 3])

In [11]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
m.shape

(3, 3)

In [13]:
print(m[1][2])
print(m[0][0])
print(m[0][1])

6
1
2


In [24]:
t = np.array([
    [
        [[1],[2]],
        [[3],[4]],
        [[5],[6]]
    ]
    ,
    [
        [[7],[8]],
        [[9],[10]],
        [[11],[12]]
    ]
    ,[
        [[13],[14]]
        ,[[15],[16]]
        ,[[17],[17]]
    ]
])

In [25]:
t.shape

(3, 3, 2, 1)

In [31]:
m=m/5
print(m)

[[  6.   7.   8.]
 [  9.  10.  11.]
 [ 12.  13.  14.]]


In [33]:
m*=0
m+=5

In [34]:
m*=m

In [35]:
print(m)

[[ 25.  25.  25.]
 [ 25.  25.  25.]
 [ 25.  25.  25.]]
